### ISSUE TITLE
wav声音文件的vad agc算法如能封装成 arduino library就好了

### ISSUE THREAD

**Issue by lixy123** [cpuimage/WebRTC_VAD#1]
我是个人电子爱好者,业务时间用价格低廉的智能芯片ESP32开发智能音箱,尝试做点有趣的东西. 目前已成功在arduino环境完成wav语音采集,百度声音文字识别,图灵服务机器对话等, 对wav底层算法不熟悉, 缺少wav音量提升算法(用于提升百度文字识别率),wav静音检测及唤醒词算法(用于触发录音识别).  如你能将c算法封装成arduino可用的库, 我可以把最新的方案和算法和你交换.
前期做了一些尝试,在这里 https://github.com/lixy123/ESP32-Audio/ 不过主要是用树莓派后端处理语音, 还不够廉价, 目前考虑用最便宜的esp32板加i2s数字麦克风完成全部工作,总价格控制在50元内.

**Comment by cpuimage** [comment]
@lixy123 你好,最近特别忙,github的一些bugs都没时间修.做到arduino环境下,理论上不难,就是目前时间精力有限.可以给我发邮件:gaozhihan@vip.qq.com,github很少上来回复.

**Comment by lixy123** [comment]
多谢回复, 便捷式伪智能音箱基本完工,用的是声音峰值当唤醒词, 效果还行. 源码已共享https://github.com/lixy123/ESP32-AUDIO-REC  欢迎一起探讨语音技术
